# Generated by Django 3.2.13 on 2022-06-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220606_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.category'),
        ),
    ]
